name: attendance

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  attendance:
    uses: enpitsuLin/skland-daily-attendance/.github/workflows/schedule.yml@main
    secrets:
      SKLAND_TOKENS: ${{ secrets.SKLAND_TOKENS }}
      SKLAND_NOTIFICATION_URLS: ${{ secrets.SKLAND_NOTIFICATION_URLS }}
      SKLAND_ANONYMOUS: ${{ secrets.SKLAND_ANONYMOUS }}
      MAX_RETRIES: ${{ secrets.MAX_RETRIES }}